name: Deploy to EKS

on:
  workflow_dispatch:  
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActionsSession
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: diigoo-arth # your ECR repository name
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}        
          IMAGE_TAG: ${{ github.sha }}
          REPOSITORY: diigoo-arth # your ECR repository name
          EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
        run: |
          sed -i.bak "s|DOCKER_IMAGE|$ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG|g" deployment.yaml
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

# name: CI/CD for EKS
# on: workflow_dispatch
# # on:
# #   push:
# #     branches: [ master ]
    
# jobs:
#   build:
#     name: CI/CD for for app deployment on EKS
#     runs-on: ubuntu-latest

#     permissions:
#       id-token: write
#       contents: read

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4.2.2

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v4
#       with:
#         role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
#         role-session-name: GitHubActionsSession
#         aws-region: ${{ secrets.AWS_REGION }}

#     - name: Login to Amazon ECR
#       id: login-ecr
#       uses: aws-actions/amazon-ecr-login@v2

#     - name: Build, tag, and push docker image to Amazon ECR
#       id: build-image
#       env:
#         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#         ECR_REPOSITORY: diigoo-arth
       
#       run: |
#         # Build and push Docker image to ECR with build number tag
#         git_hash=$(git rev-parse --short "$GITHUB_SHA")
#         IMAGE_TAG=${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}
#         echo "Building image with tag: $IMAGE_TAG"

#         docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
#         echo "Pushing image to ECR..."
#         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

#         echo "IMAGE_NAME=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

#     # - name: Update Version
#     #   run: |
#     #       git_hash=$(git rev-parse --short "$GITHUB_SHA")
#     #       version=$(cat ./charts/helm/values.yaml | grep version: | awk '{print $2}')
#     #       sed -i "s/$version/${GITHUB_REF##*/}-$git_hash/" ./charts/helm/values.yaml
          
#     # - name: Commit and push changes
#     #   uses: devops-infra/action-commit-push@v0.3
#     #   with:
#     #     github_token: ${{ secrets.GITHUB_TOKEN }}
#     #     commit_message: Version updated 
  
#     - name: Update kube config
#       run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

#     - name: Deploy to EKS
#       env:
#         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#         EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
#       run: |
#         sed -i.bak "s|DOCKER_IMAGE|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" deployment.yaml
#         kubectl apply -f deployment.yaml
#         kubectl apply -f service.yaml
#       #  kubectl rollout status deployment/nginx-deployment
